# Generated by Django 5.0.9 on 2024-11-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="amigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Formulario",
            fields=[
                ("idFormulario", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idUsuario", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Campo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("pergunta", models.CharField(max_length=255)),
                (
                    "formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campos",
                        to="respostasJa.formulario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespostaFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_resposta", models.DateTimeField(auto_now_add=True)),
                (
                    "formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_formulario",
                        to="respostasJa.formulario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="respostas_formulario",
                        to="respostasJa.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespostaCampo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.TextField()),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="respostasJa.campo",
                    ),
                ),
                (
                    "resposta_formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_campos",
                        to="respostasJa.respostaformulario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="formulario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formularios",
                to="respostasJa.usuario",
            ),
        ),
    ]
