# Generated by Django 5.0.9 on 2024-11-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("respostasJa", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="amigo",
        ),
    ]
